FLASK_APP = app
FLASK_ENV = development

DB_ENGINE = mysql

MYSQL_HOST = 127.0.0.1
MYSQL_PORT = 3306
MYSQL_USERNAME = waff
MYSQL_PASSWORD = waff1234
MYSQL_DATABASE = waff
MYSQL_CHARSET = utf8mb4

MSSQL_HOST = 192.168.1.57
MSSQL_PORT = 1433
MSSQL_USERNAME = sa
MSSQL_PASSWORD = waff!23
MSSQL_DATABASE = WEB_BLOG

# SECRET_KEY=your_secret_key
# JWT_SECRET_KEY=your_jwt_secret

